### ISSUE TITLE
nix-ld breaks if executable contains a TLS section

### ISSUE THREAD

**Issue by Mic92** [Mic92/nix-ld#8]
```console
$ readelf -l zoom/opt/zoom/zoom

Elf file type is DYN (Shared object file)
Entry point 0x479b2f
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R E    0x8
  INTERP         0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000043b1db2 0x00000000043b1db2  R E    0x200000
  LOAD           0x00000000043b27b0 0x00000000045b27b0 0x00000000045b27b0
                 0x000000000018ca88 0x000000000028c818  RW     0x200000
  DYNAMIC        0x00000000045182c8 0x00000000047182c8 0x00000000047182c8
                 0x00000000000003f0 0x00000000000003f0  RW     0x8
  NOTE           0x000000000000028c 0x000000000000028c 0x000000000000028c
                 0x0000000000000044 0x0000000000000044  R      0x4
  TLS            0x00000000043b27b0 0x00000000045b27b0 0x00000000045b27b0
                 0x0000000000000010 0x0000000000000010  R      0x8
  GNU_EH_FRAME   0x0000000003a899d0 0x0000000003a899d0 0x0000000003a899d0
                 0x000000000012d084 0x000000000012d084  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000043b27b0 0x00000000045b27b0 0x00000000045b27b0
                 0x000000000016f850 0x000000000016f850  R      0x1
$ gdb ./zoom/opt/zoom/zoom
#0  0x00007ffff7ff8941 in memcpy () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7ff8c6d in __copy_tls () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7ff8e09 in static_init_tls () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7ff4e5f in __init_libc () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7ff4f7d in __libc_start_main () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7ff470a in _start () from /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in ?? ()
#7  0x00007fffffffa87e in ?? ()
#8  0x0000000000000000 in ?? ()
```

Why does it fail and can we disable force musl to ignore this section?

**Comment by Mic92** [comment]
Fixed in https://github.com/Mic92/nix-ld/commit/1d723e63d3cd2ba3b4371d4400921811a0fd6d4a
